// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAfZGA8o1ZC4coeGvNUt0yH5SEJADbb3EI',
    appId: '1:740783345726:android:69e7a27e2ec2650a39c16f',
    messagingSenderId: '740783345726',
    projectId: 'radio-juventud-a6f6e',
    storageBucket: 'radio-juventud-a6f6e.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDqs1Asdpn6niGbxDbP5nvtl2QfXuLOomU',
    appId: '1:740783345726:ios:e4aaad547126fda539c16f',
    messagingSenderId: '740783345726',
    projectId: 'radio-juventud-a6f6e',
    storageBucket: 'radio-juventud-a6f6e.firebasestorage.app',
    androidClientId: '740783345726-2846durfu4r5osfcu6b16jkkc9204bnv.apps.googleusercontent.com',
    iosClientId: '740783345726-6rbfu6va7h0h61r9h44gofhndm3lui4f.apps.googleusercontent.com',
    iosBundleId: 'com.juventud.palabramiel',
  );
}
